app:
 appname: sgm-employee-Microservice
 logging:
    path: C:/Users/giris/logs/

spring:
 datasource:
  url: jdbc:h2:mem:testdb;
  driverClassName: org.h2.Driver
  username: sa
  password:
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
 profiles:
    active: LOCAL
#temporary data storage
#spring.datasource.url: jdbc:h2:mem:testdb
 
# temporary data storage
#spring.datasource.url: jdbc:h2:file:/data/sample
#spring.datasource.url: jdbc:h2:file:C:/data/sample (Windows only)

# Enabling H2 Console
spring.h2.console.enabled: true
 
# Custom H2 Console URL
spring.h2.console.path: /h2

# Whether to enable trace output.
spring.h2.console.settings.trace: false
 
# Whether to enable remote access.
spring.h2.console.settings.web-allow-others: false

# Set logging levels
log4j:
  logger:
    org:
      hibernate:
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: 'ERROR'

logging:
  level:
    com:
      sgm:
        microservice: WARN
    org:
      hibernate: INFO
      springframework: INFO

management:
 endpoint:
  loggers:
   enabled: true
 endpoints:
  web:
   exposure:
    include: "*"