DROP TABLE IF EXISTS TBL_DEPARTMENT;
DROP TABLE IF EXISTS TBL_EMPLOYEES;

 
CREATE TABLE TBL_DEPARTMENT (
 dept_id INT PRIMARY KEY,
 dept_name VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  dept_id INT DEFAULT NULL,
  email VARCHAR(250) NOT NULL,
  salary INT NOT NULL,
  CONSTRAINT fk_dept_id
    FOREIGN KEY (dept_id)
    REFERENCES TBL_DEPARTMENT (dept_id)
);
